services: 
    api:
        build: 
            dockerfile: ./API/Employee.API/Dockerfile
            no_cache: true
        container_name: api
        ports:
            - "8080:8080"
        depends_on:
            sqlserver:
                restart: true
                condition: service_started
    sqlserver:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
          - ACCEPT_EULA=Y
          - MSSQL_SA_PASSWORD=admPass&123
        ports:
          - "1433:1433"
    react-app:
        build:
            no_cache: true
            context: ./UI/employee-management
        ports:
            - "3000:3000"
        depends_on:
            api:
              condition: service_started
      